[package]
name = "abc"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
argon2 = {version="0.5.3", features=["std"]}
secp256k1 = {version="0.31.1", features=["std", "rand", "hashes", "global-context"]}
sha3 = "0.10.8"
